---
- name: Install Docker using apt
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install docker.io package
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: yes